name: Release

on: workflow_dispatch

jobs:
  ic-ui-kit-release:
    name: "Release develop -> main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create PR
        run: |
          echo 'VERSION=1.1.0' >> $GITHUB_ENV
          echo ${{ env.VERSION }}
          git stash
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/jd239/main-test-repo-1/pulls" -d '{"title":"Develop -> Main","body":"${{ env.VERSION }}","head":"develop","base":"main"}'
      # - name: Create develop -> main PR
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     title: "develop -> main"
      #     body: >
      #       Version: ${{ env.VERSION }}
      #     branch: origin/main
      #     base: origin/develop
