name: Release

on: workflow_dispatch

jobs:
  ic-ui-kit-release:
    name: "Release develop -> main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: browser-actions/setup-chrome@latest
      - name: get version
        run: |
          git checkout -b release-check
          echo 'version=1.1.0' >> $GITHUB_ENV
          git stash
          git checkout develop
      - name: Create develop -> main PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "develop -> main"
          body: >
            Version: ${{ env.VERSION }}
          branch: origin/main
          base: origin/develop